import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from "next/script";
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Connect & Find Your Trezor',
    description: 'Generated by Gemini',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                 <Script id="tawkto-chat" strategy="afterInteractive">
              {`
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/68e39690a72e3519521839c9/1j6sg8a5v';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `}
            </Script>
                </body>
        </html>
    );
}